// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plsebkepwbteyubkbewg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsc2Via2Vwd2J0ZXl1YmtiZXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMjAwMjQsImV4cCI6MjA3Nzc5NjAyNH0.J6kBpBjPp2C-2be1RHiOFARM2y8Pft1hCjSAeia7OO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});